language: node_js

node_js:
    - '12'

sudo: required
addons:
    chrome: stable

env:
    global:
        - CODECOV_TOKEN="38702dcb-0848-4a8a-a1d3-f97f0197a193"

before_install:
    - npm cache clean --force
    - npm i -g npm@6.9.0
    - npm i -g codecov

install:
    - npm ci

script:
    - npm run build
    - npm run test:unit
    - npm run test:cypress

after_success:
    - npm run codecov
